from typing import Optional, Callable, Type, List, Dict, Any
from llm.adapters import BaseLlmAdapter
import logging
from models import Finding, Findings

from pydantic import BaseModel

import re

logger = logging.getLogger(__name__)

class FaikeAdapter(BaseLlmAdapter):
    def __init__(self, base_url: str, model: str = None, api_key: Optional[str] = None, thinking: str = "medium"):
        super().__init__(thinking=thinking)
        self.model = model
        self.model_name = self.model
        self.model_vendor = 'Fake AI LLM'

    async def prompt_structured(self, system_prompt: str, user_prompt: str, response_format: Type[BaseModel], tool_fns: Optional[List[Callable]] = None) -> BaseModel:
        logger.getChild(self.__class__.__name__).debug("prompt_structured initial response", extra={'prompt': user_prompt})

        if response_format is Findings:
            # Extract the real filename from user_prompt, allowing future steps to work
            filename_match = re.search("(?<=File: )(.*?)(?=\\n)", user_prompt)
            if filename_match:
                filename = filename_match.group(0)
            else:
                list_item_match = re.search(r"^- (.+)$", user_prompt, re.MULTILINE)
                filename = list_item_match.group(1) if list_item_match else "app.py"
            fake_finding: dict[str: any] = {
                "file": filename,
                "snippet": "[]",
                "title": "Fake Issue #1234",
                "issue": "Fake Issue",
                "recommendation": "Do Nothing",
                "validation_steps": ["Inspect the fake finding in app.py.", "Confirm no real validation is required for Faike."],
                "cwe": "CWE-NAN",
                "priority": 0,
                "line_number": 1,
            }
            
            return Findings(findings=[Finding.model_validate(fake_finding)])

        if hasattr(response_format, "model_fields") and "skills" in response_format.model_fields:
            return response_format.model_validate(
                {
                    "skills": [
                        {
                            "filename": "application-routing.md",
                            "content": "# Application Routing\n\nGenerated by Faike AI for command-path testing.",
                        }
                    ]
                }
            )
            
        else: #Currently prompt_structured only accepts Findings as a return type
            logger.error(f"Invalid response_format {response_format} passed to prompt_structured (faike.py)")
            raise Exception(f"Invalid response_format {response_format} passed to prompt_structured (faike.py)")

        

    async def prompt(self, system_prompt: str, user_prompt: str, tool_fns: Optional[List[Callable]] = None) -> str | None:
        return "\nFake Summary"

    def generate_agent(self, system_prompt: str = None, tool_fns: Optional[List[Callable]] = None):
        #Faike LLM: Certified non-existent AI doesn't support interactive mode
        return None
