import uuid

from . import ModelInterface
from ..tools import Tool
from ..roles import Message, MessageRole
from models import Findings
from typing import Any, AsyncGenerator, Type, override
import re
import logging

logger = logging.getLogger(__name__)

class FaikeInterface(ModelInterface):
    adapter: None # type: ignore

    def __init__(self):
        pass

    @property
    @override
    def model_name(self) -> str:
        return "Faike"

    @override
    async def run(self, _input: list[Message], additional_tools: list[Tool] = []) -> list[Message]:
        return [msg async for msg in self._iter_run(_input, additional_tools)]

    @override
    async def _iter_run(self, _input: list[Message], additional_tools: list[Tool] = []) -> AsyncGenerator[Message, None]:
        response_format: Type = str
        for tool in additional_tools:
            if tool.name == "respond":
                response_format = tool.args["response"].annotation

        user_prompt = ""
        for msg in _input:
            if isinstance(msg, MessageRole.User):
                user_prompt = msg.content
                break

        filename_match = re.search(r"(?<=File: )(.*?)(?=\n)", user_prompt)
        if filename_match:
            filename = filename_match.group(0)
        else:
            list_item_match = re.search(r"^- (.+)$", user_prompt, re.MULTILINE)
            filename = list_item_match.group(1) if list_item_match else "app.py"

        fake_data: Any = {}

        if response_format is Findings:
            fake_data = {"findings":
                [{
                    "file": filename,
                    "snippet": "[]",
                    "title": "Fake Issue #1234",
                    "issue": "Fake Issue",
                    "recommendation": "Do Nothing",
                    "validation_steps": ["Inspect the fake finding in app.py.", "Confirm no real validation is required for Faike."],
                    "cwe": "CWE-NAN",
                    "priority": 0,
                    "line_number": 1,
                }]
            }
        elif hasattr(response_format, "model_fields") and "skills" in response_format.model_fields:
            fake_data = {
                "skills": [
                    {
                        "filename": "application-routing.md",
                        "content": "# Application Routing\n\nGenerated by Faike AI for command-path testing.",
                    }
                ]
            }
        elif response_format is str:
            fake_data = "Fake Summary"
        else:
            fake_data = {}

        yield MessageRole.ToolCall(tool_name="respond", arguments={"response":fake_data}, tool_call_id=str(uuid.uuid4()), original={})
