name: Build and publish release on new tag
on:
  push:
    tags:
      - '*'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: punksecurity
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
        id: version
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push SAIST-Lite
        run: |
          docker buildx build . \
            --push \
            --progress=plain \
            --tag docker.io/punksecurity/saist:lite-${{ steps.version.outputs.version }} \
            --tag docker.io/punksecurity/saist:lite-latest \
            --platform linux/amd64
            --target saist
      - name: Build and push SAIST
        run: |
          docker buildx build . \
            --push \
            --progress=plain \
            --tag docker.io/punksecurity/saist:${{ steps.version.outputs.version }} \
            --tag docker.io/punksecurity/saist:latest \
            --platform linux/amd64
            --target saist-tex
